### ISSUE TITLE
Error: Cannot publish on branch gh-pages

### ISSUE THREAD

**Issue by mkjsix** [helaili/jekyll-action#113]
We have an error publishing our branch fo repository https://github.com/SoftInstigate/restheart-website 

```
Bundle complete! 5 Gemfile dependencies, 33 gems now installed.
Bundled gems are installed into `./vendor/bundle`
Configuration file: /github/workspace/_config.yml
            Source: /github/workspace
       Destination: /github/workspace/build
 Incremental build: disabled. Enable with --incremental
      Generating... 
                    done in 3.778 seconds.
 Auto-regeneration: disabled. Use --watch to enable.
Jekyll build done
Error: Cannot publish on branch gh-pages
```

the workflow is super simple:

```
on:
  push

jobs:
  jekyll:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    # Use GitHub Actions' cache to shorten build times and decrease load on servers
    - uses: actions/cache@v2
      with:
        path: vendor/bundle
        key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile') }}
        restore-keys: |
          ${{ runner.os }}-gems-
    # Standard usage
    - uses:  helaili/jekyll-action@v2
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
```

What are we missing?
