### ISSUE TITLE
Breaking change to the `bundle build` command, output folder path changed and can't access

### ISSUE THREAD

**Issue by Ligengxin96** [helaili/jekyll-action#127]
This is git action output on Jan 14 2022.

![picture 1](https://user-images.githubusercontent.com/46650314/156364488-642b9765-298d-49b3-8df7-9b16411c40a2.png)
<div align="center"> picture 1 </div>

And this is git action output on Mar 2 2022.

![picture 2](https://user-images.githubusercontent.com/46650314/156364947-2babf356-1f56-4bfd-a626-867982200adc.png)
<div align="center"> picture 2 </div>

We can see (line 56 in picture 1 and line 57 in picture 2),  the build command output folder path changed from `/github/workspace/build` to `/github/jekyll_build`

And I check the git action output info, the docker mount folders are
 `-v "/var/run/docker.sock":"/var/run/docker.sock"` 
` -v "/home/runner/work/_temp/_github_home":"/github/home" `
`-v "/home/runner/work/_temp/_github_workflow":"/github/workflow" `
`-v "/home/runner/work/_temp/_runner_file_commands":"/github/file_commands" `
`-v "/home/runner/work/BlogSrc/BlogSrc":"/github/workspace"`

So, we can access `/github/workspace/build`  because the `/github/workspace` folder has been mounted. But `/github` folder not. So we can't access the `/github/jekyll_build` folder. But we expect to access the output folder.

**Comment by Ligengxin96** [comment]
Ok, I read the doc. And I found the solution to change the output folder. Add `jekyll_build_options` param.

```yml
    # Standard usage
    - uses: helaili/jekyll-action@v2
      with:
        token: ${{ secrets.JEKYLL_PAT }}
        jekyll_build_options: "--destination ./build"
```

 Then the output folder will become `/github/workspace/build`
