### ISSUE TITLE
Can't deploy site to GitHub pages

### ISSUE THREAD

**Issue by EmilySeville7cfg** [helaili/jekyll-action#133]
Hello! When I want to deploy [my personal site](https://github.com/EmilySeville7cfg/EmilySeville7cfg.github.io) I obtain [this](https://github.com/EmilySeville7cfg/EmilySeville7cfg.github.io/runs/6258298549?check_suite_focus=true#step:4:10) error:

```
The minimal-mistakes-jekyll theme could not be found. (Jekyll::Errors::MissingDependencyException)
```

How to fix this problem? Everything works locally. My [cd.yml](https://github.com/EmilySeville7cfg/EmilySeville7cfg.github.io/blob/master/.github/workflows/cd.yml) is:

```yml
name: Continuous Deployment
on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  github-pages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile') }}
          restore-keys: "{{ runner.os }}-gems-"
      - uses: helaili/jekyll-action@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
```

I've used [this](https://jekyllrb.com/docs/continuous-integration/github-actions/) template and slightly changed it: I used new versions of actions.

I use `Ruby 2.7.0p0` and Jekyll `4.2.2`.
