### ISSUE TITLE
Images not being added to `gh-pages` branch

### ISSUE THREAD

**Issue by Timecrash** [helaili/jekyll-action#142]
I've ported a WordPress blog to Jekyll using `jekyll-action@2.4.0` and wanted to make a new blog post to test the functionality. I added an image to `assets/images/2022/09/_DSC0086.jpg`, referenced it in said blog post, and commited to GitHub.

For some reason, the image isn't being added to the `gh-pages` branch at all. It's in the `main` branch just fine:

![image](https://user-images.githubusercontent.com/15052506/188031150-205640e3-3d96-4ad1-9d5d-8095804b5b47.png)

But not in the `gh-pages` branch:

![image](https://user-images.githubusercontent.com/15052506/188031186-b488432a-ec89-4b0d-9891-9f5fa979f24b.png)

I really don't know what the issue could be, or if this action is even where the problem is. I didn't see any specific settings I had to use, and the images I uploaded when I first made the blog worked without issue.

Here's the workflow file, I just copied and pasted it:

```yaml
name: Build and deploy Jekyll site to GitHub Pages

on:
  push:
    branches:
      - main # or master before October 2020

jobs:
  github-pages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile') }}
          restore-keys: |
            ${{ runner.os }}-gems-
      - uses: helaili/jekyll-action@2.4.0    # Choose any one of the Jekyll Actions
        with:                                # Some relative inputs of your action
          token: ${{ secrets.GITHUB_TOKEN }}
```
