### ISSUE TITLE
Breaks when trying to install dart-sass-embedded

### ISSUE THREAD

**Issue by ProfaneServitor** [helaili/jekyll-action#150]
When I try to deploy a site using github actions, and it uses sass, this error appears:
```
Fetching html-pipeline 2.14.3
Installing html-pipeline 2.14.3
Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

current directory:
/github/workspace/vendor/bundle/ruby/2.7.0/gems/sass-embedded-1.57.1/ext/sass
/usr/local/bin/ruby -I/usr/local/lib/ruby/2.7.0/rubygems -rrubygems
/github/workspace/vendor/bundle/ruby/2.7.0/gems/rake-13.0.6/exe/rake
RUBYARCHDIR\=/github/workspace/vendor/bundle/ruby/2.7.0/extensions/x86_64-linux-musl/2.7.0/sass-embedded-1.57.1
RUBYLIBDIR\=/github/workspace/vendor/bundle/ruby/2.7.0/extensions/x86_64-linux-musl/2.7.0/sass-embedded-1.57.1
rake aborted!
NotImplementedError: sass_embedded for x86_64-linux-musl not available at
https://github.com/sass/dart-sass-embedded/releases/tag/1.57.1
/github/workspace/vendor/bundle/ruby/2.7.0/gems/sass-embedded-1.57.1/ext/sass/Rakefile:226:in
`default_sass_embedded'
/github/workspace/vendor/bundle/ruby/2.7.0/gems/sass-embedded-1.57.1/ext/sass/Rakefile:21:in
`block (2 levels) in <top (required)>'
/github/workspace/vendor/bundle/ruby/2.7.0/gems/sass-embedded-1.57.1/ext/sass/Rakefile:21:in
`fetch'
/github/workspace/vendor/bundle/ruby/2.7.0/gems/sass-embedded-1.57.1/ext/sass/Rakefile:21:in
`block in <top (required)>'
/github/workspace/vendor/bundle/ruby/2.7.0/gems/rake-13.0.6/exe/rake:27:in
`<main>'
Tasks: TOP => default => install => embedded.rb => sass_embedded
(See full trace by running task with --trace)

rake failed, exit code 1
```

github-pages.yml:
```yaml
name: Build and deploy Jekyll site to GitHub Pages

on:
  push:
    branches:
      - main # or master before October 2020

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  jekyll:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    # Use GitHub Actions' cache to shorten build times and decrease load on servers
    - uses: actions/cache@v2
      with:
        path: vendor/bundle
        key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile') }}
        restore-keys: |
          ${{ runner.os }}-gems-

    # Standard usage
    - uses:  helaili/jekyll-action@v2
      with:
        token: ${{ secrets.YOUR_CUSTOM_TOKEN }}
```

Specifying direct links to repository, or placing a copy in vendor doesn't work either. It stubbornly tries to pull from the same place anyway.
```ruby
# Gemfile
gem 'sass-embedded', git: 'https://github.com/ntkme/sass-embedded-host-ruby.git' # Completely ignored
```
