### ISSUE TITLE
Fails with `error: src refspec  does not match any`

### ISSUE THREAD

**Issue by Philzen** [helaili/jekyll-action#30]
No matter what i try, [my action runs](https://github.com/B-FfF/stadtwerk-mit-zukunft/runs/655103732) always end up with:

```
error: src refspec ***@github.com/B-FfF/stadtwerk-mit-zukunft.git does not match any
error: failed to push some refs to 'https://'
```

What i've tried so far:
1. as Github Pages were served from `master` branch before, the repository did not have a `gh-pages` branch yet. I manually created a [`gh-pages`](https://github.com/B-FfF/stadtwerk-mit-zukunft/tree/gh-pages) branch as an empty orphan branch containing only one commit.
2. Initial plan was to deploy from `development` branch, so i switched back the script to only fire on master pushes as its done in the standard tutorial.

Both did not fix the issue, issue remains exactly the same. As i would like to avoid having to rollback my whole project to jekyll 3.x, help will be highly appreciated.

The action is as follows:

```
name: Jekyll to GitHub Pages CI

on:
  push:
    branches:
      - master

jobs:
  github-pages:
    runs-on: ubuntu-16.04
    steps:
      - name: 🛎 Check out master
        uses: actions/checkout@v2

      # Use GitHub Actions' cache to shorten build times and decrease load on servers
      - name: 📁 Init gem cache
        uses: actions/cache@v1
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}

      - name: 🔨 Build for Github-Pages
        uses: helaili/jekyll-action@2.0.1
        env:
          JEKYLL_PAT: ${{ secrets.JEKYLL_PAT }}
```
