### ISSUE TITLE
Error with Invalid date not allowing site to be built

### ISSUE THREAD

**Issue by karmanyaahm** [helaili/jekyll-action#43]
Hi, I'm trying to implement this action on my repository at [https://github.com/Beachwood-High-School/beachwood-high-school.github.io](https://github.com/Beachwood-High-School/beachwood-high-school.github.io).

This is the workflows file I'm using:  
```
name: JekyllPublish
 
on:
  push:
    branches: 
      - code-master
    
jobs:
  jekyll:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    # Use GitHub Actions' cache to shorten build times and decrease load on servers
    - uses: actions/cache@v1
      with:
        path: vendor/bundle
        key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-gems-
    # Standard usage
    - uses:  helaili/jekyll-action@2.0.3
      env:
        JEKYLL_PAT: ${{ secrets.JEKYLL_PAT }}
```

When I the action runs, this is part of the logs:  

```

 Configuration file: ./_config.yml
            Source: .
       Destination: build
 Incremental build: disabled. Enable with --incremental
      Generating... 
             Error: could not read file /github/workspace/vendor/bundle/ruby/2.7.0/gems/jekyll-3.8.7/lib/site_template/_posts/0000-00-00-welcome-to-jekyll.markdown.erb: Invalid date '<%= Time.now.strftime('%Y-%m-%d %H:%M:%S %z') %>': Document 'vendor/bundle/ruby/2.7.0/gems/jekyll-3.8.7/lib/site_template/_posts/0000-00-00-welcome-to-jekyll.markdown.erb' does not have a valid date in the YAML front matter.
             ERROR: YOUR SITE COULD NOT BE BUILT:
                    ------------------------------------
                    Invalid date '<%= Time.now.strftime('%Y-%m-%d %H:%M:%S %z') %>': Document 'vendor/bundle/ruby/2.7.0/gems/jekyll-3.8.7/lib/site_template/_posts/0000-00-00-welcome-to-jekyll.markdown.erb' does not have a valid date in the YAML front matter.

```

I don't understand why that is happening since I can build the website locally and I don't have a `_posts` directory in my website. I'm using this action so I can use more Jekyll extensions in the future. My goal is to have jekyll in the 'code-master' branch and the raw html, css, and js in the master branch so it can be published using Github pages.

Thanks
