### ISSUE TITLE
The target_branch argument is unavailable

### ISSUE THREAD

**Issue by UlyssesZh** [helaili/jekyll-action#53]
```
##[warning]Unexpected input(s) 'target_branch', valid inputs are ['entryPoint', 'args', 'jekyll_src']
```
In the workflow yml file:
```
      - name: Deploy Jekyll
        uses: helaili/jekyll-action@2.0.1
        env:
          JEKYLL_PAT: ${{ secrets.JEKYLL_PAT }}
        with:
          target_branch: master
```
