### ISSUE TITLE
Does `build_only: true` - now require github credentials  ? 

### ISSUE THREAD

**Issue by nrdlab** [helaili/jekyll-action#86]
HI am i wrong or now Github credential are mandatory also for `build_only : true`  mode ? 

### latest commit 
https://github.com/helaili/jekyll-action/blob/2d65375c43ffce8b175a3155a538a13a742e04ea/entrypoint.sh#L75

### CI config 
```yml 

       - uses: helaili/jekyll-action@v2
        with:
          build_only: true
          jekyll_src: './docs'

```
### Error  

![image](https://user-images.githubusercontent.com/16638949/111601289-82118400-87d2-11eb-8527-7fefe571d945.png)
