### ISSUE TITLE
Using Alternate Branch as Source

### ISSUE THREAD

**Issue by atneya** [helaili/jekyll-action#96]
Apologies if I missed this in the documentation, but is there support for configuring the *source* branch (not the deploy branch) for this action. I would like to use main as by source branch rather than master.

**Comment by helaili** [comment]
The source branch is wherever you trigger the Actions workflow from:
```
on:
  push:
    branches:    
      - <your source branch>
...
```
